# -*- coding: utf-8 -*-
"""
/***************************************************************************
 ShipwreckFinder
                                 A QGIS plugin
 This plugin finds shipwrecks from multibeam sonar data.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-02-16
        copyright            : (C) 2024 by NOAA
        email                : anjashep@umich.edu
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load ShipwreckFinder class from file ShipwreckFinder.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .shipwreck_finder import ShipwreckFinder
    return ShipwreckFinder(iface)
